### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'data/data.json'

### ISSUE THREAD

**Issue by AntonioCayulao** [amelbakry/kdave-chart#3]
Hello,
I'm not sure if this is the same error or related to #2 but I have a problem with the permissions with the kdave pod:
The error:

```
$ kubectl logs kdave-767947cdf6-ldfhg  -n kdave -f

[2022-08-09 23:22:59,776| INFO| MainProcess] Starting kdave server.
[2022-08-09 23:22:59,777| INFO| MainProcess] Running on http://0.0.0.0:8000/
[2022-08-09 23:22:59,797| INFO| flask-app] child process calling self.run()
[2022-08-09 23:22:59,798| INFO| helm-handler] child process calling self.run()
[2022-08-09 23:23:39,838| INFO| helm-handler] Fetching helm releases to update the current data.
[2022-08-09 23:23:52,724| INFO| helm-handler] Checking the used apiVersions for release: elasticsearch
[2022-08-09 23:23:54,075| INFO| helm-handler] Checking the used apiVersions for release: grafana
[2022-08-09 23:23:54,153| INFO| helm-handler] Checking the used apiVersions for release: kdave
[2022-08-09 23:23:54,465| INFO| helm-handler] Checking the used apiVersions for release: kibana
[2022-08-09 23:23:55,733| INFO| helm-handler] Checking the used apiVersions for release: prometheus
[2022-08-09 23:23:56,090| INFO| helm-handler] Checking the used apiVersions for release: sonarqube-lts
[2022-08-09 23:23:58,073| INFO| helm-handler] Data file is outdated or doesn't exist. Building a new data file
[2022-08-09 23:23:58,073| INFO| helm-handler] Writing data to data file: data/data.json
[2022-08-09 23:23:58,074| INFO| helm-handler] process shutting down
Process helm-handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/exporter/app.py", line 863, in export_deprecated_versions_metrics
    get_deprecations_for_all_releases(
  File "/app/exporter/app.py", line 782, in get_deprecations_for_all_releases
    update_data_file(data_file, app_data=app_data)
  File "/app/exporter/app.py", line 799, in update_data_file
    file.save(json.dumps(dict(app_data)))
  File "/app/exporter/helper.py", line 65, in save
    with open(self.file_name, "w+") as fd:
PermissionError: [Errno 13] Permission denied: 'data/data.json'
[2022-08-09 23:23:58,077| INFO| helm-handler] process exiting with exitcode 1
```

The version inside the pod is:
```
app@kdave-767947cdf6-ldfhg:/app$ cat /app/exporter/__init__.py
__version__ = "0.2.3"
```

And, when I see the permissions, inside the container, all are to root user, but the [psp](https://github.com/amelbakry/kdave-chart/blob/main/templates/psp.yaml#L16) is for non-root:
```
app@kdave-767947cdf6-ldfhg:/app$ ls -la
total 132
drwxr-xr-x 1 app  app     18 Aug  9 23:22 .
drwxr-xr-x 1 root root    39 Aug  9 23:22 ..
-rw-r--r-- 1 root root    50 May 31 12:00 .bandit
-rw-r--r-- 1 root root 16384 May 31 12:44 .coverage
-rw-r--r-- 1 root root 16384 May 31 12:44 .coverage.7327394232b4.9.130401
-rw-r--r-- 1 root root   102 May 31 12:00 .flake8
drwxr-xr-x 7 root root   169 May 31 12:59 .git
drwxr-xr-x 5 root root   114 May 31 12:59 .github
-rw-r--r-- 1 root root  4186 May 31 12:00 .gitignore
-rw-r--r-- 1 root root   112 May 31 12:00 .isort.cfg
-rw-r--r-- 1 root root   229 May 31 12:00 .markdownlint.json
drwxr-xr-x 3 root root    17 May 31 12:59 .mypy_cache
drwxr-xr-x 3 root root    70 May 31 12:59 .pytest_cache
-rw-r--r-- 1 root root   307 May 31 12:00 CHANGELOG.md
-rw-r--r-- 1 root root  5489 May 31 12:00 CODE_OF_CONDUCT.md
-rw-r--r-- 1 root root  2631 May 31 12:00 CONTRIBUTING.md
-rw-r--r-- 1 root root    63 May 31 12:00 MAINTAINERS.md
-rw-r--r-- 1 root root    17 May 31 12:00 MANIFEST.in
-rw-r--r-- 1 root root 10777 May 31 12:06 README.md
-rw-r--r-- 1 root root  1544 May 31 12:00 SECURITY.md
drwxr-xr-x 2 root root    27 May 31 12:59 config
drwxr-xr-x 3 root root  4096 Aug  9 23:22 data
drwxr-xr-x 2 root root   138 May 31 12:59 docker
-rw-r--r-- 1 root root   623 May 31 12:00 docker-compose.yaml
drwxr-xr-x 2 root root    62 May 31 12:59 docs
drwxr-xr-x 3 root root   151 May 31 12:59 exporter
drwxr-xr-x 2 root root    98 May 31 12:59 grafana
drwxr-xr-x 2 root root  4096 May 31 12:59 htmlcov
drwxr-xr-x 2 root root   185 May 31 12:59 images
-rw-r--r-- 1 root root    62 May 31 12:00 mypy.ini
-rw-r--r-- 1 root root   100 May 31 12:00 pyproject.toml
-rw-r--r-- 1 root root   110 May 31 12:00 pytest.ini
-rw-r--r-- 1 root root   138 May 31 12:00 requirements-test.txt
-rw-r--r-- 1 root root   141 May 31 12:11 requirements.txt
-rw-r--r-- 1 root root  1729 May 31 12:00 setup.py
drwxr-xr-x 4 root root   142 May 31 12:59 tests
```

I have seen the dockerfiles:

-  ./docker/kdave-server.dockerfile
-  ./docker/kdave-service.dockerfile
-  ./docker/kdave.dockerfile

And I suggest changing the copy layer:
[COPY . /app](https://github.com/wayfair-incubator/kdave/blob/main/docker/kdave-server.dockerfile#L32)

by this:
COPY --chown=${USER_NAME}:${USER_NAME} . /app

Thank you!
Greetings!

**Comment by amelbakry** [comment]
Hello Antonio, Thanks for reporting this issue
I added the `fsGroup` to set the correct permission on the volume https://github.com/amelbakry/kdave-chart/blob/main/values.yaml#L41. Please check now

**Comment by amelbakry** [comment]
Stefan confirmed the fix https://github.com/amelbakry/kdave-chart/issues/2
